services:
  web:
    build:
      context: .  # The context is the current directory with the Dockerfile for Django
    command: gunicorn haskellishardai_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./data/db.sqlite3:/Backend/db.sqlite3  # Persist the SQLite database
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static  # Serve static files
    ports:
      - "8080:80"
    depends_on:
      - web


